"""add compatibility_reason and conversation_starter to matches

Revision ID: 5a6a732ade7a
Revises: 5f1947dd3ab2
Create Date: 2025-11-14 08:33:03.727603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6a732ade7a'
down_revision: Union[str, Sequence[str], None] = '5f1947dd3ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('compatibility_reason', sa.Text(), nullable=True))
    op.add_column('matches', sa.Column('conversation_starter', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'conversation_starter')
    op.drop_column('matches', 'compatibility_reason')
    # ### end Alembic commands ###
