"""add token_version to users

Revision ID: a006327f06e4
Revises: dfb7aa430725
Create Date: 2025-11-13 16:09:06.791543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a006327f06e4'
down_revision: Union[str, Sequence[str], None] = 'dfb7aa430725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Add column with a default value (0) for existing rows
    op.add_column(
        'users',
        sa.Column('token_version', sa.Integer(), server_default='0', nullable=False)
    )

    # 2. Remove the server_default for future inserts (optional but clean)
    op.alter_column('users', 'token_version', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
